version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "7001:4141"
    volumes:
      - ./server:/usr/src/server
  client:
    build:
      context: ./client
    ports:
      - "7002:3000"
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
  bujit-db:
    container_name: bujit-db
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27018:27017"
  redis_db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis/conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
volumes:
  data:
