version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - 7001:3000
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
  client:
    build:
      context: ./client
    ports:
      - 7002:3000
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
